name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t anjana-ci-demo .

      - name: Test Container Run
        run: docker run -d --name test-app anjana-ci-demo
                  sleep 5
                  docker logs test-app
                  docker stop test-app


